数据手册
=========

* `ESP32-S3-WROOM-1-N16R8`_ (Datasheet)
* `OLED Display Module`_ (Datasheet)
* `SA868`_ (Datasheet)
* `Slide and Rotary Encoder Switches`_ (Datasheet)

.. _ESP32-S3-WROOM-1-N16R8: https://www.espressif.com.cn/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_cn.pdf
.. _OLED Display Module: ../../../../datasheet/SPEC X096-2864KSWPG17-C30 VER A.pdf
.. _SA868: ../../../../datasheet/SA868 2W嵌入式小体积对讲机模块V1.2.pdf
.. _Slide and Rotary Encoder Switches: ../../../../datasheet/Slide and Rotary Encoder Switches.pdf

.. https://www.espressif.com.cn/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf
