name: Build PlatformIO

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/**"
      - "examples/**"
      - ".github/workflows/platformio.yml"
      - "platformio.ini"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/Factory
          - examples/GPS_Basic_Example
          - examples/GPS_Full_Example
          - examples/Pixels_RGBWstrandtest
          - examples/Pixels_Strandtest_Example
          - examples/SA868_ATDebug_Example
          - examples/SA868_ESPSendAudio_Example
          - examples/SD_Test_Example
          - examples/SD_Time_Example
          - examples/TFT_ArcFill_Example
          - examples/TFT_Keypad_240x320_Example
          - examples/U8g2_FontUsage_Example
          - examples/U8g2_GraphicsTest_Example
          - examples/U8g2_UpdateArea_Example
          - examples/WAV_Player

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO
        run: pio run
        env:
          PLATFORMIO_SRC_DIR: ${{ matrix.example }}
